@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.2 (64-bit)
REM
REM Filename    : elaborate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for elaborating the compiled design
REM
REM Generated by Vivado on Sun Jan 03 04:06:57 +0300 2021
REM SW Build 2708876 on Wed Nov  6 21:40:23 MST 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: elaborate.bat
REM
REM ****************************************************************************
echo "xelab -wto 9769360d898943cda61d77f6fdb9025b --incr --debug typical --relax --mt 2 -L xil_defaultlib -L secureip --snapshot tb_computer_behav xil_defaultlib.tb_computer -log elaborate.log"
call xelab  -wto 9769360d898943cda61d77f6fdb9025b --incr --debug typical --relax --mt 2 -L xil_defaultlib -L secureip --snapshot tb_computer_behav xil_defaultlib.tb_computer -log elaborate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
